assert `acquirerId`
digitalbazaar/bedrock-resource-restriction pull request #5
Opened 2020-09-30 21:47 UTC by JSAssassin

addresses #4

2020-09-30 22:12 UTC, dlongley requested changes
We need similar checks for the other functions too.

2020-09-30 23:33 UTC, dmitrizagidulin approved these changes
:+1: 
thanks @JSAssassin!

2020-10-01 16:31 UTC, dlongley approved these changes
LGTM other than some minor style nits to be addressed. Thanks!

2020-10-01 16:36 UTC, mandyvenables approved these changes

2020-10-05 15:24 UTC, JoshDunnDev approved these changes

2020-10-05 15:29 UTC, merged